import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  UserButton,
  SignedOut,
} from "@clerk/nextjs";
import "./globals.css";
import { Inter as FontSans, Inter } from "next/font/google";
import { auth } from "@clerk/nextjs/server";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Medical Invoice",
  description: "Generated by your father",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>Medical Invoice</title>
          <meta name="description" content={"Generated by your father"} />
          <link rel="icon" href="/medicalogo.jpg" />
        </Head>
        <body className={inter.className}>
          {" "}
          {!userId && (
            <div className="w-screen flex justify-center my-[2em]">
              <Button variant="outline">
                {" "}
                <SignedOut>
                  <SignInButton />
                </SignedOut>
              </Button>
            </div>
          )}
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
